### ISSUE TITLE
Links sometimes fail to load

### ISSUE THREAD

**Issue by KitsuneofDreams** [yoshinoa/aramscript#5]
I believe it's related to pulling Aurora, but sometimes links never load. You see a black page with "Loading..."

example - https://www.shurimashuffle.com/teams?data=eyJibHVlVGVhbSI6WyJKYXJ2YW5JViIsIlNrYXJuZXIiLCJTZWp1YW5pIiwiU2V0dCIsIkNob2dhdGgiLCJWb2xpYmVhciIsIkhlY2FyaW0iLCJVcmdvdCIsIkxlZVNpbiIsIkRyYXZlbiIsIk5pZGFsZWUiLCJCcmlhciIsIlplZCIsIkVra28iLCJNYWxwaGl0ZSJdLCJ0aW1lc3RhbXAiOiIyMDI0LTA4LTA3VDIwOjQ4OjE1LjE4N1oiLCJsYW5nIjoiZW5fVVMiLCJzb2xvdGVhbSI6dHJ1ZX0=

**Comment by yoshinoa** [comment]
Hi, thanks for opening this, I'll take a look

**Comment by yoshinoa** [comment]
Fixed. Let me know if you have any more issues.

**Comment by KitsuneofDreams** [comment]
Thank you!
